### ISSUE TITLE
oc-fetch-ssh-keys seems to try to execute authorized_keys2

### ISSUE THREAD

**Issue by dragon2611** [scaleway/image-tools#109]
Created a new Ubuntu 14.04 instance yesterday, it seems the oc-fetch-ssh-keys script is trying to execute authorized_keys2 for some reason

If the file is now present it throws the following error

```
oc-fetch-ssh-keys --update
/usr/local/sbin/oc-fetch-ssh-keys: line 17: /root/.ssh/authorized_keys2: No such file or directory
```

If you create the file

```
root@irc2-test:~# oc-fetch-ssh-keys --update
/usr/local/sbin/oc-fetch-ssh-keys: line 17: /root/.ssh/authorized_keys2: Permission denied
```
If you allow execute on the file

```
root@irc2-test:~# oc-fetch-ssh-keys --update
/root/.ssh/authorized_keys2: line 1: ssh-rsa: command not found
```

Interestingly I don't see functionality relating to authorized keys on one of my older instances so presumably this is a newer functionality?

**Comment by QuentinPerez** [comment]
Hi @dragon2611 

Thanks for your feedback, I found the bug https://github.com/scaleway/image-tools/blob/master/skeleton-common/usr/local/sbin/oc-fetch-ssh-keys#L30 we must escape [ **`** ], I will fix it but you can do it manually and retry 😊

**Comment by dragon2611** [comment]
That fixes the error but I'm not entirely sure if recent versions of openSSH still use the authorized_keys2 file as it's deprecated

**Comment by QuentinPerez** [comment]
Yes, it's deprecated but it works again with  ```SSH-2.0-OpenSSH_6.7p1``` version

**Comment by dragon2611** [comment]
It did not seem to on OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3

**Comment by dragon2611** [comment]
Ignore my last comment, The permissions on the authorized_keys2 file were wrong, seems to need chmod 644 after creation

**Comment by dragon2611** [comment]
I believe this is now resolved as the instance_keys file now provides a way to import the keys into the main file, thanks for that :+1: 

https://github.com/scaleway/image-tools/commit/2e6f8c52137eba746a72c436dd48526067410c5f
