### ISSUE TITLE
Review the sysv branch

### ISSUE THREAD

**Issue by moul** [scaleway/image-tools#12]
Build a new Debian image and check for requirements

- [x] boot
- [x] reboot
- [ ] multi nbd

**Comment by aimxhaisse** [comment]
@todo: check if multi-nbd is ok (I don't remember)

**Comment by aimxhaisse** [comment]
@todo: consider removing $local_fs from Required-Start of nbd-add-extra-volumes (thanks to buxy on IRC)

**Comment by rhertzog** [comment]
I had to change the meta-information in the init script to have a good boot ordering on a Debian Wheezy system:
```
root@eos:~# grep Required-Start /etc/init.d/nbd-add-extra-volumes 
# Required-Start:           checkroot-bootclean
root@eos:~# grep Required-Start: /etc/init.d/checkfs.sh 
# Required-Start:    checkroot nbd-add-extra-volumes
root@eos:~# update-rc.d nbd-add-extra-volumes enable
update-rc.d: using dependency based boot sequencing
```

**Comment by moul** [comment]
:ok_hand:
