### ISSUE TITLE
scw run fails silently when no resources are available

### ISSUE THREAD

**Issue by ScrumpyJack** [scaleway/image-tools#126]
scw run --name="buildcowsay" builder

If I understand it correctly, this should be run from within a scaleway image (not from my local desktop - don't know why not) and it creates a new C1 called buildcowsay, starts it and run the builder command inside it.
Can we have better docs for the image-tools and the image-builder process?

The above command (assuming I'm using it properly) fails silently. Not enough resources? or am I missing something else here

**Comment by moul** [comment]
Hi @ScrumpyJack, we noticed this problem (silent failure) and opened an issue on the scaleway-cli repo, see https://github.com/scaleway/scaleway-cli/issues/229

For now, I suggest you to play with the `--timeout` flag, which can be reasonably set to --timeout=200 seconds to avoid false positive timeouts

@QuentinPerez, about the documentation, can you list here the actual documentations listing ? @QuentinPerez what do you think about creating an hello-world demo video ?

**Comment by QuentinPerez** [comment]
Hi @ScrumpyJack 

You can find the instructions [here](https://github.com/scaleway/image-tools/tree/master/image-builder)
As you can see, there are 3 prompts:
 > `root@yourmachine>` the commands must be executed on your local desktop
 > `root@buildcowsay>` on a C1 server
 > `root@your_custom_image>` on a C1 server with the image that you have crafted

@moul I think the demo video is a good idea :)

**Comment by moul** [comment]
I'm closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue.

Thank you!
