### ISSUE TITLE
Script oc-swapfile do not work

### ISSUE THREAD

**Issue by matunixe** [scaleway/image-tools#147]
Under Alpine Linux image, the script to create and enable a swapfile don't work. I get the following errors:

``/usr/local/sbin/oc-swapfile: line 26: fallocate: command not found``
``chmod: /swapfile: No such file or directory``
``mkswap: can't open '/swapfile': No such file or directory``
``swapon: can't stat '/swapfile': No such file or directory``

**Comment by moul** [comment]
I will try to get a workaround for alpine linux :)

cc @aimxhaisse

**Comment by moul** [comment]
@matunixe the solution is to install `fallocate`, on alpine linux:

```console
$ apk add util-linux
```

I will update the script to trigger a comprehensive ⚠️ inviting the user to install `util-linux` instead of crashing
