### ISSUE TITLE
`modprobe` is not working

### ISSUE THREAD

**Issue by moul** [scaleway/image-tools#154]
Original issue: https://github.com/scaleway/image-archlinux/issues/27
Related with: https://github.com/scaleway/kernel-tools/issues/207

**Comment by iPerky** [comment]
what kernel should I use in the boot script to install ip_tables and ufw?
```
modprobe ip_tables
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.4.4-std-1
```

**Comment by moul** [comment]
Hi @iPerky ,

I just tried with the two following bootscripts:

4.4.5-docker #1:

```console
root@ecstatic-meitner:~# uname -a
Linux ecstatic-meitner 4.4.5-docker-1 #1 SMP Fri Mar 11 10:17:21 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@ecstatic-meitner:~# modprobe ip_tables
```

---

4.4.4-std #3 

```console
root@small-kowalevski:~# uname -a
Linux small-kowalevski 4.4.4-std-3 #1 SMP Tue Mar 8 17:31:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@small-kowalevski:~# modprobe ip_tables
```

**Comment by iPerky** [comment]
Hello

Sorry forgot to mention, I'm running on armv7l
```
uname -a
Linux arm 4.4.4-std-1 #1 SMP Sun Mar 6 18:34:13 UTC 2016 armv7l GNU/Linux
```

**Comment by moul** [comment]
Ok, I will add missing modules and rebuild one

I will update this ticket when the new kernels will be released
