### ISSUE TITLE
Image on ImageHub up to date?

### ISSUE THREAD

**Issue by meyskens** [scaleway/image-tools#157]
On the ImageHub I saw version 1.3 of the Image Builder for over several months while here multiple things have been changed (like multi arch). Does this image need updating or is it up to date? (In the last case a new version number might be a good  idea to let people know there have been changes)

**Comment by moul** [comment]
Hi @meyskens, the current "Image Builder" at version 1.3 is not yet multiarch compliant, however, you can still build armhf images

We will release a new version soon with multiarch support and new features, stay tuned !

**Comment by meyskens** [comment]
Great :smile:

**Comment by moul** [comment]
If you need an update in the meantime, i.e, bumping Docker, do not hesitate to ping us

**Comment by meyskens** [comment]
Just adding the `armhf-` seems to work fine for building images but thanks!

**Comment by moul** [comment]
I'm actually rebuilding/releaseing all the images with the new multiarch support

Closing this issue as it should be addressed, reply here if needed
