### ISSUE TITLE
give a try to go-nbd

### ISSUE THREAD

**Issue by aimxhaisse** [scaleway/image-tools#16]
https://github.com/frostschutz/go-nbd/

- full static (can be embedded easily in initrd and packaged for all our distribution without too much pain)
- small (we can extend it if needed)

Open questions:

- does it handle disconnections properly?
- is it stable?
- is it fast enough ?
- is it cpu/memory wasteful ?

**Comment by moul** [comment]
xnbd-client is working quite well for now

`go-nbd` may be interesting if we need to develop new features over the NBD protocol
