### ISSUE TITLE
BUG - Missing escape character in commented text in scw-fetch-ssh-keys script

### ISSUE THREAD

**Issue by weberkai** [scaleway/image-tools#193]
Hi!

At line 25 in scw-fetch-ssh-keys script, bash is executing a commented command.
This cause Slackware ARM 14.2 minirootfs to never fetch ssh keys.

Please, may you add escape character "backslash" before "$"? Thank you!

`#   -- Add keys using server tags - https://cloud.scaleway.com/#/servers/\$(scw-metadata --cached ID)`

https://github.com/scaleway/image-tools/blob/0a76640703b0caab371ddc5e9b68d4c281aa5570/skeleton-common/usr/local/sbin/scw-fetch-ssh-keys#L25

**Comment by tbillon** [comment]
> At line 25 in scw-fetch-ssh-keys script, bash is executing a commented command.

AFAIK neither bash nor any other shells execute commented lines as this would break 100% of shell scripts.

**Comment by weberkai** [comment]
It's a commented text inside a heredoc.
Opened another issue with correct diagnostic.
Thank you.

**Comment by weberkai** [comment]
https://github.com/scaleway/image-tools/issues/194
