### ISSUE TITLE
BUG - Missing complete path to  scw-metadata in scw-fetch-ssh-keys script

### ISSUE THREAD

**Issue by weberkai** [scaleway/image-tools#194]
Hi!

At line 25 in scw-fetch-ssh-keys script, bash is executing a command inside a heredoc.
This cause Slackware ARM 14.2 minirootfs to never fetch ssh keys.

Please, may you add escape character "backslash" before "$"? Thank you!

`#   -- Add keys using server tags - https://cloud.scaleway.com/#/servers/\$(scw-metadata --cached ID)`

--
Edited:
The error described here is incorrect! See below!

https://github.com/scaleway/image-tools/blob/0a76640703b0caab371ddc5e9b68d4c281aa5570/skeleton-common/usr/local/sbin/scw-fetch-ssh-keys#L25

**Comment by tbillon** [comment]
Hum I don't think this is a bug. I understand that it isn't working for you but I think the intention here is to provide a direct like to your server from the `.ssh/authorized_keys` file (event if the link is broken… but this I can fix).
Plus are you sure it's `bash` ? This is pretty common shell so even older or simpler shells should handle it correctly. For instance this is something we do in the initrd with buildroot's shell. This is probably linked to #192 .

**Comment by weberkai** [comment]
Hi!

I think I will change suggested solution...

It's better to quote or escape "heredoc limiting text" in line 17:
(...) << \EOF (...) or
(...) << "EOF" (...) or
(...) << 'EOF' (...)

This way, subshell is never called:
http://tldp.org/LDP/abs/html/here-docs.html#EX71C

Please, could change it?
Thanks!

**Comment by weberkai** [comment]
Hi!

You mean the expansion is intentional and linked to issue 192?

Then I should edit like this:

#   -- Add keys using server tags - https://cloud.scaleway.com/#/servers/$(/usr/local/sbin/scw-userdata/scw-metadata --cached ID)

?

**Comment by weberkai** [comment]
Hi!

You're correct! Changed like proposed above, and worked! And the final link is really broken.

So, please, could you correct the link and add complete path?

# -- Add keys using server tags - https://cloud.scaleway.com/#/servers/$(/usr/local/bin/scw-metadata --cached ID)

Lines 37 and 40 already have complete path, but line 25 not.

Thanks.

**Comment by weberkai** [comment]
Hi!

Now I'm calling scripts like this and errors are gone:
```

PATH=$PATH:/usr/local/bin:/usr/local/sbin /usr/local/sbin/scw-gen-machine-id
PATH=$PATH:/usr/local/bin:/usr/local/sbin /usr/local/sbin/scw-generate-ssh-keys
PATH=$PATH:/usr/local/bin:/usr/local/sbin /usr/local/sbin/scw-fetch-ssh-keys
PATH=$PATH:/usr/local/bin:/usr/local/sbin /usr/local/bin/scw-check-kernel
PATH=$PATH:/usr/local/bin:/usr/local/sbin /usr/local/sbin/scw-sync-kernel-modules
```

**Comment by tbillon** [comment]
Glad you found a solution. You can just set your PATH globally with the command `export PATH=$PATH:/usr/local/bin:/usr/local/sbin` and then call all scripts without using their full path.
