### ISSUE TITLE
Tune xnbd-client to be oom adjusted

### ISSUE THREAD

**Issue by aimxhaisse** [scaleway/image-tools#21]
nbd-client handles this internally so it's really xnbd-client specific, the idea is to prevent the oom-killer to kill xnbd-client under high memory load.

Credits to ConSi on IRC.

**Comment by moul** [comment]
:+1:

**Comment by moul** [comment]
Done in initrd for /dev/nbd0

**Comment by moul** [comment]
Since xnbd-client is now only handled in the INITRD, this issue is now fully fixed
