### ISSUE TITLE
Make a debian/ubuntu .deb package

### ISSUE THREAD

**Issue by moul** [scaleway/image-tools#3]

**Comment by lukas2511** [comment]
+1

would like this (also packages for archlinux and other distros)

**Comment by moul** [comment]
Hi @lukas2511, do you have documentation for packaging in archlinux please ? or maybe a demonstration repository ?
Thanks

**Comment by lukas2511** [comment]
Have a look at AUR (https://aur.archlinux.org/)
Tons of example PKGBUILD files there.

Here is the official documentation: https://wiki.archlinux.org/index.php/Creating_packages

**Comment by aimxhaisse** [comment]
https://github.com/jordansissel/fpm
