### ISSUE TITLE
Investigate why check-kernel fails on Ubuntu with kernel 4.0.5-std

### ISSUE THREAD

**Issue by aimxhaisse** [scaleway/image-tools#41]
Boot logs:

    Starting SCW kernel requirements checker...
    Warning: this image expects a Linux kernel >= 3.7 (you are using 4.0.5-233) ; consider using another scaleway bootscript.

**Comment by moul** [comment]
Fixes one point of https://github.com/scaleway/image-app-docker/issues/19
