### ISSUE TITLE
Allow cross-build of images using internal aptitude mirrors

### ISSUE THREAD

**Issue by QuentinPerez** [scaleway/image-tools#42]
Current behavior:

- using the binfmt-support, we can run docker build
- apt-get update ... mirror.scaleway.com won't work outside of the network

Expected behavior:

- apt-get update should be dynamic or at least skip down mirrors

**Comment by moul** [comment]
:+1:

**Comment by moul** [comment]
Fixed in Ubuntu: https://github.com/scaleway/image-ubuntu/commit/0c8e178e73a5a15d4ff10bc75da5471ad6777c54
and in Debian: https://github.com/scaleway/image-debian/commit/22da2e1d009616a9d74eebe1705ca2b85d5328e9
