### ISSUE TITLE
Allow booting an image with a temporary ssh key

### ISSUE THREAD

**Issue by moul** [scaleway/image-tools#45]
- [x] https://github.com/scaleway/scaleway-cli/blob/master/examples/create-image-from-s3.sh#L26: add a new tag like this: `TAGS_0=SSH_AUTHORIZED_KEY=ssh-rsa_AAAAB3NzaC1yc2EAAAADAQ...` (without space)
- [x] https://github.com/scaleway/image-tools/blob/master/skeleton-common/usr/local/sbin/oc-fetch-ssh-keys: check for tag(s) `SSH_AUTHORIZED_KEY`

**Comment by QuentinPerez** [comment]
create-image-from-s3 -> https://github.com/scaleway/scaleway-cli/commit/09dfb8b20f1851e072c7adad5aa11e2c5227ddaa
