### ISSUE TITLE
Unable to create image

### ISSUE THREAD

**Issue by vikbez** [scaleway/image-tools#73]
root@image-builder:/tmp# ./create-image-from-s3.sh http://store.scw.42.am/scw/scw-minecraft-1.0.0.tar
[+] URL of the tarball: http://store.scw.42.am/scw/scw-minecraft-1.0.0.tar
[+] Target name: scw-minecraft-1.0.0-2015-09-03_13:40
[+] Creating new server in rescue mode with a secondary volume...
[+] Server created: 3fe0ab69-1322-4190-aab2-5d78d82254c4
[+] Booting...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x12066c]

goroutine 5 [running]:
github.com/scaleway/scaleway-cli/pkg/api.WaitForServerState(0x10748f40, 0x1070b830, 0x24, 0x3c19c0, 0x7, 0x0, 0x0, 0x0)
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/api/helpers.go:392 +0x80
github.com/scaleway/scaleway-cli/pkg/api.WaitForServerReady.func1(0x10749500, 0x10724648, 0x10724650, 0x10748f40, 0x1070b830, 0x24, 0x0, 0x0)
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/api/helpers.go:417 +0x78
created by github.com/scaleway/scaleway-cli/pkg/api.WaitForServerReady
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/api/helpers.go:445 +0xd0

goroutine 1 [runnable]:
github.com/scaleway/scaleway-cli/pkg/api.WaitForServerReady(0x10748f40, 0x1070b830, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/api/helpers.go:449 +0x320
github.com/scaleway/scaleway-cli/pkg/commands.RunExec(0xb6e43138, 0x107240c0, 0xb6e431c0, 0x107240c8, 0xb6e431c0, 0x107240d0, 0x1070c1e0, 0x14, 0x14, 0x1070a108, ...)
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/commands/exec.go:53 +0x198
github.com/scaleway/scaleway-cli/pkg/cli.runExec(0x562340, 0x1070a108, 0x2, 0x3, 0x0, 0x0)
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/cli/cmd_exec.go:57 +0x190
github.com/scaleway/scaleway-cli/pkg/cli.Start(0x1070a0f8, 0x4, 0x5, 0x1070f900, 0x0, 0x0, 0x0)
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/cli/main.go:113 +0xbb0
main.main()
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/cmd/scw/main.go:16 +0x90

goroutine 24 [select]:
net/http.(*persistConn).writeLoop(0x109861e0)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:1009 +0x314
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:686 +0xad0

goroutine 23 [IO wait]:
net.runtime_pollWait(0xb6e446a0, 0x72, 0x10710090)
	/usr/local/Cellar/go/1.5/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x108434b8, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x108434b8, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10843480, 0x10863000, 0x1000, 0x1000, 0x0, 0xb6e3f030, 0x10710090)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x109b83d0, 0x10863000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/net.go:172 +0xc8
crypto/tls.(*block).readFromUntil(0x10a0cae0, 0xb6e44878, 0x109b83d0, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/crypto/tls/conn.go:455 +0xc8
crypto/tls.(*Conn).readRecord(0x1077a9c0, 0x453417, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/crypto/tls/conn.go:540 +0x240
crypto/tls.(*Conn).Read(0x1077a9c0, 0x109b1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/crypto/tls/conn.go:901 +0x13c
net/http.noteEOFReader.Read(0xb6e48d80, 0x1077a9c0, 0x1098620c, 0x109b1000, 0x1000, 0x1000, 0x1ffd84, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:1370 +0x5c
net/http.(*noteEOFReader).Read(0x109ed150, 0x109b1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x10b34ab0)
	/usr/local/Cellar/go/1.5/libexec/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x10b34ab0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x109861e0)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:876 +0xe4
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:685 +0xab4

**Comment by vikbez** [comment]
works when updating scw-cli to 1.4.0

**Comment by moul** [comment]
Thanks for reporting
